Dl 71 grid averaging and 10min windspeeds
reaskearth/api pull request #29
Opened 2024-02-15 03:14 UTC by nicreask

2024-02-15 21:51 UTC, mizuguta approved these changes
LGTM

2024-02-16 00:57 UTC, jasonre0 commented on tools/get_tcwind_csv.py
> +        elif regird_op == 'median':
regird - ? typo ?

2024-02-16 00:58 UTC, jasonre0 requested changes
lgtm except for the regird defect.

2024-02-16 05:10 UTC, mizuguta commented
Unit-tests failed due to 400 HTTP error. Does it mean we need to update api-server as well?

2024-02-19 02:11 UTC, mizuguta approved these changes
LGTM.

2024-02-19 02:17 UTC, merged